### ISSUE TITLE
another crash...

### ISSUE THREAD

**Issue by mathieujobin** [vincepii/konsole-multi-terminal#10]
I split horizontally once,

I split the right side twice vertically.

I worked for a while...

eventually I closed the two extra split on the right side, so I have only two terminal side by side.

then I split the right side again

crashed...

```
Application: Konsole (konsole), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7ff32cb097c0 (LWP 23832))]

Thread 2 (Thread 0x7ff317110700 (LWP 23833)):
#0  pthread_mutex_unlock (mutex=0x7ff310000a60) at forward.c:194
#1  0x00007ff3266709c1 in g_mutex_unlock () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff32662e718 in g_main_context_prepare () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff32662ef03 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ff32662f0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ff32afe47be in QEventDispatcherGlib::processEvents (this=0x7ff3100008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:436
#6  0x00007ff32afb60af in QEventLoop::processEvents (this=this@entry=0x7ff31710fde0, flags=...) at kernel/qeventloop.cpp:149
#7  0x00007ff32afb63a5 in QEventLoop::exec (this=this@entry=0x7ff31710fde0, flags=...) at kernel/qeventloop.cpp:204
#8  0x00007ff32aeb2c5f in QThread::exec (this=this@entry=0xd09a70) at thread/qthread.cpp:537
#9  0x00007ff32af97823 in QInotifyFileSystemWatcherEngine::run (this=0xd09a70) at io/qfilesystemwatcher_inotify.cpp:265
#10 0x00007ff32aeb532f in QThreadPrivate::start (arg=0xd09a70) at thread/qthread_unix.cpp:349
#11 0x00007ff326f15182 in start_thread (arg=0x7ff317110700) at pthread_create.c:312
#12 0x00007ff32c44c30d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7ff32cb097c0 (LWP 23832)):
[KCrash Handler]
#5  0x00007ff32a38e5d3 in QWidget::hasFocus (this=0xec9300) at kernel/qwidget.cpp:6363
#6  0x00007ff32c0bd843 in Konsole::MultiTerminalDisplayManager::getFocusedMultiTerminalDisplay (this=0xa2d870, mtd=<optimized out>) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/MultiTerminalDisplayManager.cpp:372
#7  0x00007ff32c107e53 in Konsole::ViewManager::createMultiTerminalView (this=this@entry=0xa2d310, orientation=orientation@entry=Qt::Horizontal) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/ViewManager.cpp:804
#8  0x00007ff32c10821d in Konsole::ViewManager::multiTerminalHorizontal (this=0xa2d310) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/ViewManager.cpp:564
#9  0x00007ff32c109bc5 in Konsole::ViewManager::qt_static_metacall (_o=0xec9300, _id=17750448, _a=0x7fff11a75d20, _c=<optimized out>) at /home/mathieu/Projects/KDE/konsole-multi-terminal/build/src/ViewManager.moc:188
#10 0x00007ff32afcb87a in QMetaObject::activate (sender=sender@entry=0xa6b4f0, m=m@entry=0x7ff32adfade0 <QAction::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fff11a75d20) at kernel/qobject.cpp:3539
#11 0x00007ff32a34aa62 in QAction::triggered (this=this@entry=0xa6b4f0, _t1=false) at .moc/release-shared/moc_qaction.cpp:276
#12 0x00007ff32a34c433 in QAction::activate (this=0xa6b4f0, event=<optimized out>) at kernel/qaction.cpp:1257
#13 0x00007ff32afcfc1e in QObject::event (this=0xa6b4f0, e=<optimized out>) at kernel/qobject.cpp:1194
#14 0x00007ff32a34c4f2 in QAction::event (this=<optimized out>, e=<optimized out>) at kernel/qaction.cpp:1187
#15 0x00007ff32b92be9f in KAction::event(QEvent*) () from /usr/lib/libkdeui.so.5
#16 0x00007ff32a350e2c in QApplicationPrivate::notify_helper (this=this@entry=0x912f50, receiver=receiver@entry=0xa6b4f0, e=e@entry=0x115a5a0) at kernel/qapplication.cpp:4567
#17 0x00007ff32a3574a0 in QApplication::notify (this=0x7fff11a765a0, receiver=0xa6b4f0, e=0x115a5a0) at kernel/qapplication.cpp:4353
#18 0x00007ff32ba01baa in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5
#19 0x00007ff32afb74dd in QCoreApplication::notifyInternal (this=0x7fff11a765a0, receiver=receiver@entry=0xa6b4f0, event=event@entry=0x115a5a0) at kernel/qcoreapplication.cpp:953
#20 0x00007ff32afbab3d in sendEvent (event=0x115a5a0, receiver=0xa6b4f0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#21 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x85b020) at kernel/qcoreapplication.cpp:1577
#22 0x00007ff32afbafe3 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1470
#23 0x00007ff32afe4f83 in sendPostedEvents () at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:236
#24 postEventSourceDispatch (s=0x90c380) at kernel/qeventdispatcher_glib.cpp:287
#25 0x00007ff32662ee04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ff32662f048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ff32662f0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ff32afe47a1 in QEventDispatcherGlib::processEvents (this=0x85c9a0, flags=...) at kernel/qeventdispatcher_glib.cpp:434
#29 0x00007ff32a3f2bb6 in QGuiEventDispatcherGlib::processEvents (this=<optimized out>, flags=...) at kernel/qguieventdispatcher_glib.cpp:204
#30 0x00007ff32afb60af in QEventLoop::processEvents (this=this@entry=0x7fff11a76470, flags=...) at kernel/qeventloop.cpp:149
#31 0x00007ff32afb63a5 in QEventLoop::exec (this=this@entry=0x7fff11a76470, flags=...) at kernel/qeventloop.cpp:204
#32 0x00007ff32afbbb79 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1225
#33 0x00007ff32a34f37c in QApplication::exec () at kernel/qapplication.cpp:3828
#34 0x00007ff32c72e417 in kdemain (argc=1, argv=0x7fff11a766d8) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/main.cpp:86
#35 0x00007ff32c372ec5 in __libc_start_main (main=0x4006d0 <main(int, char**)>, argc=1, argv=0x7fff11a766d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff11a766c8) at libc-start.c:287
#36 0x00000000004006fe in _start ()
```

**Comment by mathieujobin** [comment]
https://github.com/kterminal/kterminal
