### ISSUE TITLE
closing last terminal keeps window open.

### ISSUE THREAD

**Issue by mathieujobin** [vincepii/konsole-multi-terminal#8]
first of all, thank you for making this software.
hopefully I will be able to use it and maybe help as well.
I have been looking for a konsole based terminator clone for a long time.
I dont know why, but I hate using terminators, although it has all of the features I am looking for. I recently got used to iTerm2 on the Mac which is Perfect in my opinion.

enough, I am off topic.

so I cloned and compiled your software sucessfully. great.
I am launching them for the first time and I hit `CTRL-d`

which close the terminal, as you know. but it should actually terminate the process in case this is the last open terminal.

with this grey window, I tried nonetheless to see If I could split the window...
it crashed. and here is the backtrace

```
Application: Konsole (konsole), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fadaab7f7c0 (LWP 22573))]

Thread 2 (Thread 0x7fad95384700 (LWP 22574)):
#0  0x00007fadaa4b36bd in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fada46e5c20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fada46a4b14 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fada46a4f7b in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fada46a50ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fada905a7be in QEventDispatcherGlib::processEvents (this=0x7fad900008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:436
#6  0x00007fada902c0af in QEventLoop::processEvents (this=this@entry=0x7fad95383de0, flags=...) at kernel/qeventloop.cpp:149
#7  0x00007fada902c3a5 in QEventLoop::exec (this=this@entry=0x7fad95383de0, flags=...) at kernel/qeventloop.cpp:204
#8  0x00007fada8f28c5f in QThread::exec (this=this@entry=0x2566680) at thread/qthread.cpp:537
#9  0x00007fada900d823 in QInotifyFileSystemWatcherEngine::run (this=0x2566680) at io/qfilesystemwatcher_inotify.cpp:265
#10 0x00007fada8f2b32f in QThreadPrivate::start (arg=0x2566680) at thread/qthread_unix.cpp:349
#11 0x00007fada4f8b182 in start_thread (arg=0x7fad95384700) at pthread_create.c:312
#12 0x00007fadaa4c230d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7fadaab7f7c0 (LWP 22573)):
[KCrash Handler]
#5  QHash<Konsole::Profile::Property, QVariant>::findNode (this=this@entry=0x10, akey=<optimized out>, ahp=0x0) at /usr/include/qt4/QtCore/qhash.h:884
#6  0x00007fadaa17745b in contains (akey=<synthetic pointer>, this=<optimized out>) at /usr/include/qt4/QtCore/qhash.h:874
#7  property<QVariant> (aProperty=Konsole::Profile::SaveGeometryOnExit, this=<optimized out>) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/Profile.h:565
#8  property<bool> (aProperty=Konsole::Profile::SaveGeometryOnExit, this=<optimized out>) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/Profile.h:560
#9  saveGeometryOnExit (this=<optimized out>) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/Profile.h:390
#10 Konsole::ViewManager::applyProfileToView (this=this@entry=0x231d7b0, view=view@entry=0x2547a80, profile=...) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/ViewManager.cpp:1009
#11 0x00007fadaa17da40 in Konsole::ViewManager::createAndSetupTerminalDisplay (this=0x231d7b0, session=session@entry=0x23a9270) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/ViewManager.cpp:696
#12 0x00007fadaa131a69 in Konsole::MultiTerminalDisplayManager::cloneMtd (this=0x239d520, sourceMtd=<optimized out>, container=container@entry=0x254e4f0) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/MultiTerminalDisplayManager.cpp:493
#13 0x00007fadaa17f6c2 in Konsole::ViewManager::splitView (this=0x231d7b0, orientation=Qt::Horizontal) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/ViewManager.cpp:521
#14 0x00007fadaa17fc25 in Konsole::ViewManager::qt_static_metacall (_o=0x10, _id=11, _a=0x7fff04701930, _c=<optimized out>) at /home/mathieu/Projects/KDE/konsole-multi-terminal/build/src/ViewManager.moc:182
#15 0x00007fada904187a in QMetaObject::activate (sender=sender@entry=0x22fbb10, m=m@entry=0x7fada8e70de0 <QAction::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fff04701930) at kernel/qobject.cpp:3539
#16 0x00007fada83c0a62 in QAction::triggered (this=this@entry=0x22fbb10, _t1=false) at .moc/release-shared/moc_qaction.cpp:276
#17 0x00007fada83c2433 in QAction::activate (this=0x22fbb10, event=<optimized out>) at kernel/qaction.cpp:1257
#18 0x00007fada9045c1e in QObject::event (this=0x22fbb10, e=<optimized out>) at kernel/qobject.cpp:1194
#19 0x00007fada83c24f2 in QAction::event (this=<optimized out>, e=<optimized out>) at kernel/qaction.cpp:1187
#20 0x00007fada99a1e9f in KAction::event(QEvent*) () from /usr/lib/libkdeui.so.5
#21 0x00007fada83c6e2c in QApplicationPrivate::notify_helper (this=this@entry=0x21fd5b0, receiver=receiver@entry=0x22fbb10, e=e@entry=0x2465320) at kernel/qapplication.cpp:4567
#22 0x00007fada83cd4a0 in QApplication::notify (this=0x7fff047021b0, receiver=0x22fbb10, e=0x2465320) at kernel/qapplication.cpp:4353
#23 0x00007fada9a77baa in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5
#24 0x00007fada902d4dd in QCoreApplication::notifyInternal (this=0x7fff047021b0, receiver=receiver@entry=0x22fbb10, event=event@entry=0x2465320) at kernel/qcoreapplication.cpp:953
#25 0x00007fada9030b3d in sendEvent (event=0x2465320, receiver=0x22fbb10) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#26 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x2145020) at kernel/qcoreapplication.cpp:1577
#27 0x00007fada9030fe3 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1470
#28 0x00007fada905af83 in sendPostedEvents () at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:236
#29 postEventSourceDispatch (s=0x21f6c60) at kernel/qeventdispatcher_glib.cpp:287
#30 0x00007fada46a4e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007fada46a5048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007fada46a50ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007fada905a7a1 in QEventDispatcherGlib::processEvents (this=0x21469a0, flags=...) at kernel/qeventdispatcher_glib.cpp:434
#34 0x00007fada8468bb6 in QGuiEventDispatcherGlib::processEvents (this=<optimized out>, flags=...) at kernel/qguieventdispatcher_glib.cpp:204
#35 0x00007fada902c0af in QEventLoop::processEvents (this=this@entry=0x7fff04702080, flags=...) at kernel/qeventloop.cpp:149
#36 0x00007fada902c3a5 in QEventLoop::exec (this=this@entry=0x7fff04702080, flags=...) at kernel/qeventloop.cpp:204
#37 0x00007fada9031b79 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1225
#38 0x00007fada83c537c in QApplication::exec () at kernel/qapplication.cpp:3828
#39 0x00007fadaa7a4417 in kdemain (argc=1, argv=0x7fff047022e8) at /home/mathieu/Projects/KDE/konsole-multi-terminal/src/main.cpp:86
#40 0x00007fadaa3e8ec5 in __libc_start_main (main=0x4006d0 <main(int, char**)>, argc=1, argv=0x7fff047022e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff047022d8) at libc-start.c:287
#41 0x00000000004006fe in _start ()

```

**Comment by mathieujobin** [comment]
pfeww, we have a new working fork

**Comment by mathieujobin** [comment]
https://github.com/kterminal/kterminal
